### ISSUE TITLE
Contribute changes back upstream

### ISSUE THREAD

**Issue by tautropfli** [bash/portal#29]
* [x] eframe: PR merged
* [x] poll-promise: PR merged
* [x] opener: PR merged
* [x] [ico-builder](https://github.com/bash/ico-builder): Publish crate
